---
name: Build, Scan and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"
      - "README.md"
      - "scripts/**"
      - "appspec.yml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GitLeaks scan
        uses: zricethezav/gitleaks-action@v2

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-ecr-role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        env:
          ECR_REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
          REPO_NAME: ${{ vars.ECR_REPOSITORY_NAME }} 
        run: |
          docker build -t $ECR_REGISTRY/$REPO_NAME:${{ github.sha }} .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
          sudo mv ./bin/trivy /usr/local/bin/trivy
          trivy --version

      - name: Scan Docker image with Trivy
        env:
          ECR_REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
          REPO_NAME: ${{ vars.ECR_REPOSITORY_NAME }}
        run: |
          trivy image \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            $ECR_REGISTRY/$REPO_NAME:${{ github.sha }}

      - name: Tag & Push Docker image
        env:
          ECR_REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
          REPO_NAME: ${{ vars.ECR_REPOSITORY_NAME }}
        run: |
          docker tag $ECR_REGISTRY/$REPO_NAME:${{ github.sha }} $ECR_REGISTRY/$REPO_NAME:latest
          docker push $ECR_REGISTRY/$REPO_NAME:${{ github.sha }}
          docker push $ECR_REGISTRY/$REPO_NAME:latest

      - name: Deploy to ECS (If Service Exists)
        run: |
          echo "Checking if ECS Service exists..."
          
          # Using the variables we just created in Terraform
          CLUSTER="${{ vars.CLUSTER_NAME }}"
          SERVICE="${{ vars.SERVICE_NAME }}"
          REGION="${{ vars.AWS_REGION }}"

          # Check for the service status
          SERVICE_STATUS=$(aws ecs describe-services --cluster "$CLUSTER" --services "$SERVICE" --region "$REGION" --query 'services[0].status' --output text 2>/dev/null)

          if [ "$SERVICE_STATUS" == "ACTIVE" ]; then
            echo "Service $SERVICE is ACTIVE. Triggering deployment..."
            aws ecs update-service \
              --cluster "$CLUSTER" \
              --service "$SERVICE" \
              --force-new-deployment \
              --region "$REGION"
          else
            echo "ECS Service $SERVICE not found in $CLUSTER. Skipping deployment."
            exit 0
          fi
